	    <div class="page-head">
	      <h2 class="pull-left"><i class="icon-home"></i> Dashboard</h2>

        <!-- Breadcrumb -->
        <div class="bread-crumb pull-right">
          <a href="index.html"><i class="icon-home"></i> Home</a>
          <!-- Divider -->
          <span class="divider">/</span>
          <a href="index.html#" class="bread-current">Dashboard</a>
        </div>

        <div class="clearfix"></div>

	    </div>