<footer>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <!-- Copyright info -->
                <p class="copy">
                    Copyright &copy; 2012 | <a href="index.html#">by Zend Group.</a>
                    <?php echo $this->translate('All rights reserved.'); ?>
                </p>
            </div>
        </div>
    </div>
</footer>