  	<div class="sidebar">
      	<div class="sidebar-dropdown"><a href="index.html#">Navigation</a></div>

      	<!--- Sidebar navigation -->
      	<!-- If the main navigation has sub navigation, then add the class "has_sub" to "li" of main navigation. -->
      	<ul id="nav">
        	<!-- Main menu with font awesome icon -->
	        <li><a href="index.html" class="open"><i class="icon-home"></i> Dashboard</a>
	          <!-- Sub menu markup
	          <ul>
	            <li><a href="#">Submenu #1</a></li>
	            <li><a href="#">Submenu #2</a></li>
	            <li><a href="#">Submenu #3</a></li>
	          </ul>-->
	        </li>
          <li class="has_sub"><a href="index.html#"><i class="icon-list-alt"></i> Widgets  <span class="pull-right"><i class="icon-chevron-right"></i></span></a>
            <ul>
              <li><a href="widgets1.html">Widgets #1</a></li>
              <li><a href="widgets2.html">Widgets #2</a></li>
              <li><a href="widgets3.html">Widgets #3</a></li>
            </ul>
          </li>
          <li class="has_sub"><a href="index.html#"><i class="icon-file-alt"></i> Pages #1  <span class="pull-right"><i class="icon-chevron-right"></i></span></a>
            <ul>
              <li><a href="post.html">Post</a></li>
              <li><a href="login.html">Login</a></li>
              <li><a href="register.html">Register</a></li>
              <li><a href="support.html">Support</a></li>
              <li><a href="invoice.html">Invoice</a></li>
              <li><a href="profile.html">Profile</a></li>
              <li><a href="gallery.html">Gallery</a></li>
            </ul>
          </li>
          <li class="has_sub"><a href="index.html#"><i class="icon-file-alt"></i> Pages #2  <span class="pull-right"><i class="icon-chevron-right"></i></span></a>
            <ul>
              <li><a href="media.html">Media</a></li>
              <li><a href="statement.html">Statement</a></li>
              <li><a href="error.html">Error</a></li>
              <li><a href="error-log.html">Error Log</a></li>
              <li><a href="calendar.html">Calendar</a></li>
              <li><a href="grid.html">Grid</a></li>
            </ul>
          </li>
          <li><a href="charts.html"><i class="icon-bar-chart"></i> Charts</a></li>
          <li><a href="tables.html"><i class="icon-table"></i> Tables</a></li>
	        <li><a href="forms.html"><i class="icon-tasks"></i> Forms</a></li>
          <li><a href="ui.html"><i class="icon-magic"></i> User Interface</a></li>
      	</ul>
  	</div>
