

<!--
<div class="row">

	<div class="span4">
		<h2><?php echo $this->translate('Follow Development') ?></h2>
		<p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework webiste which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="http://framework.zend.com/issues/browse/ZF2">', '</a>') ?></p>
		<p>
			<a class="btn btn-success" href="http://framework.zend.com/zf2"
				target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a>
		</p>
	</div>

	<div class="span4">
		<h2><?php echo $this->translate('Discover Modules') ?></h2>
		<p><?php echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="#">', '</a>') ?></p>
		<p>
			<a class="btn btn-success" href="http://modules.zendframework.com/"
				target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a>
		</p>
	</div>

	<div class="span4">
		<h2><?php echo $this->translate('Help &amp; Support') ?></h2>
		<p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk.2 on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk.2">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
		<p>
			<a class="btn btn-success"
				href="http://webchat.freenode.net?channels=zftalk.2" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a>
		</p>
	</div>
</div>
 -->

<section id="content" class="grid-block">
	<div id="system">
		<div class="items items-col-1 grid-block">
			<div class="grid-box width100">
				<article class="item" data-permalink=#">
					<header>
						<time datetime="2012-04-19" pubdate="">
							<span class="day">19</span> <span class="month">Apr</span> <span class="year">2012</span>
						</time>
						<h1 class="title">
							<a href=# " title="holiday impressions">holiday impressions</a>
						</h1>
						<p class="meta"></p>
					</header>
					<div class="content">
						<img class="align-left" alt="Demo Image"
							src="index_data/home_news1.jpg" height="195" width="195">
						<p>
							Get on board and check our new Subway theme! It brings you a
							modern boxed layout with a <a
								href="http://yootheme.com/demo/themes/joomla/2012/subway/index.php?option=com_content&amp;view=article&amp;id=2&amp;Itemid=2">broad
								range of options for customization</a>.
						</p>
						<p>You can choose from various color and transparency options.
							Explore many beautiful designed details like fresh typography,
							icons, CSS animations and animated backgrounds.</p>
					</div>
				</article>

				<div class="links">
					<a href=# " title="holiday impressions"> Continue Reading </a>
				</div>

				<article class="item" data-permalink=#">
					<header>
						<time datetime="2012-03-05" pubdate="">
							<span class="day">05</span> <span class="month">Mar</span> <span
								class="year">2012</span>
						</time>

						<h1 class="title">
							<a href=# " title="my new office">my new office</a>
						</h1>

						<p class="meta"></p>

					</header>
					<div class="content clearfix">
						<img class="align-left" alt="Demo Image"
							src="index_data/home_news2.jpg" height="195" width="195">
						<p>Subway theme brings you some nice custom features:</p>
						<p>Two new widgetkit styles for the Slideshow and the Gallery
							are included. Their design seamlessly fits into the theme.</p>
						<p>Also notice the fixed social toolbar, which appears if you
							hover the icon to the right of your browser window.</p>

					</div>

				</article>

				<div class="links">

					<a href=# " title="my new office"> Continue Reading </a>
				</div>
			</div>
		</div>


	</div>
</section>
