
 <ul class="breadcrumb">
<!--  	<li><span class="divider"><img src="<?php echo ASSETS_LINK . '/frontend/default/images/glyphicons/'?>glyphicons_020_home.png" width="18px" height="18px"/> <span class="divider"> ▶ </span></li>  -->
     <?php
     // iterate through the pages
     foreach ($this->pages as $key => $page):
         ?>
         <li>
             <?php
             // if this isn't the last page, add a link and the separator
             if ($key < count($this->pages) - 1):
                 ?>
                 <a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>
                 <span class="divider"> ▶ </span>
             <?php
             // otherwise, just output the name
             else:
             ?>
                 <?php echo $page->getLabel(); ?>
             <?php endif; ?>
         </li>
         <?php endforeach; ?>
 </ul>