<?php

/**
 * WDS GROUP
 *
 * @name        siderbar_right.php
 * @category    WDS
 * @package    
 * @subpackage
 * @author      Thuy Dinh Xuan <thuydx@wds.vn>
 * @copyright   Copyright (c)2008-2010 WDS GROUP. All rights reserved
 * @license     http://wds.vn/license/     WDS Software License
 * @version     $1.0$
 * Oct 9, 2012
 *
 * LICENSE
 *
 * This source file is copyrighted by WDS GROUP, full details in LICENSE.txt.
 * It is also available through the Internet at this URL:
 * http://wds.vn/license/
 * If you did not receive a copy of the license and are unable to
 * obtain it through the Internet, please send an email
 * to license@wds.vn so we can send you a copy immediately.
 *
 */

?>

				<div class="widget">
        			<h2>Link</h2>
        			<div class="widget-content list-label-widget-content">
        				<ul>
        					<li><a href="http://wds.vn" dir="ltr">WDS GROUP</a> <!-- <span dir="ltr">(2)</span>  -->
        					</li>
        					<li><a href="http://zend.vn/forum" dir="ltr">Zend VN Communicate</a>
        						<!-- <span dir="ltr">(2)</span>  --></li>
        					<li><a href="http://www.zend.com/en" dir="ltr">Zend</a> <!-- <span dir="ltr">(2)</span>  -->
        					</li>
        				</ul>
        			</div>
        		</div>

        		<div class="row">
        			<div class="span3">Donec sed odio dui. Cras justo odio, dapibus ac
        				facilisis in, egestas eget quam. Vestibulum id ligula porta felis
        				euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor
        				mauris condimentum nibh, ut fermentum mas</div>
        		</div>
        		<div class="row">
        			<div class="span3">Donec sed odio dui. Cras justo odio, dapibus ac
        				facilisis in, egestas eget quam. Vestibulum id ligula porta felis
        				euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor
        				mauris condimentum nibh, ut fermentum mas</div>
        		</div>