<?php

// autoload.php generated by Composer
if (!class_exists('Autoload\\ClassLoader', false)) {
    require __DIR__ . '/Autoload' . '/ClassLoader.php';
}

return call_user_func(function() {
    $loader = new \Autoload\ClassLoader();
    $autoloadDir = __DIR__ . '/Autoload';

    $map = require $autoloadDir . '/autoload_namespaces.php';
    foreach ($map as $namespace => $path) {
        $loader->add($namespace, $path);
    }

    $classMap = require $autoloadDir . '/autoload_classmap.php';
    if ($classMap) {
        $loader->addClassMap($classMap);
    }

    $loader->register();
	$loader->setUseIncludePath(true);
    return $loader;
});
